'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { emptyProject, EditStyle, Project } from '@/lib/contracts';
import { listProjects, saveProject } from '@/lib/storage';
const styleNames: Record<EditStyle, string> = { meme: 'Meme', calm: 'Calm', competitive: 'Competitive', 'youtube-long': 'YouTube Long' };

export default function Home() {
  const [project, setProject] = useState<Project | null>(null); const [style, setStyle] = useState<EditStyle>('youtube-long'); const [log, setLog] = useState('SYSTEM READY // pilih footage'); const [progress, setProgress] = useState(0); const [preview, setPreview] = useState('');
  useEffect(() => { listProjects().then((items) => items[0] && setProject(items[0])).catch(() => setLog('STORAGE UNAVAILABLE')); }, []);
  async function importFootage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !file.type.startsWith('video/')) return setLog('Pilih file video valid.'); const next = project ?? emptyProject(); next.style = style; next.assets = [{ id: `${next.id}:video`, name: file.name, kind: 'video', durationMs: 0, sizeBytes: file.size }]; next.updatedAt = new Date().toISOString(); setProject(next); setPreview(URL.createObjectURL(file)); await saveProject(next); setLog(`FOOTAGE READY // ${file.name}`); }
  function createProject() { const next = emptyProject(); next.style = style; setProject(next); setPreview(''); saveProject(next).then(() => setLog('PROJECT CREATED // state kosong aktif')); }
  async function analyze() { if (!project) return setLog('IMPORT FOOTAGE DULU'); setLog('ANALYZING // Luna memetakan footage'); const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, style: project.style }) }); if (!response.body) return setLog('ERROR // stream unavailable'); const reader = response.body.getReader(); const decoder = new TextDecoder(); while (true) { const chunk = await reader.read(); if (chunk.done) break; for (const line of decoder.decode(chunk.value).split('\n')) if (line.startsWith('data: ')) { const event = JSON.parse(line.slice(6)); setProgress(event.progress); setLog(`${event.state} // ${event.message}`); if (event.data?.decisions) { const updated = { ...project, decisions: event.data.decisions, updatedAt: new Date().toISOString() }; setProject(updated); await saveProject(updated); } } } }
  return <main className="shell"><header className="topbar"><span className="brand">LUNA // AI EDITOR</span><span className="status">LOCAL-FIRST / ONLINE</span></header><section className="hero"><p className="muted">WORKSPACE 01 · NEXUS MEDIA SYSTEM</p><h1>Make footage<br /><span className="accent">mean something.</span></h1><p className="muted">Editor nyata. State tersimpan lokal. Tanpa mock data.</p><div className="actions"><select aria-label="Edit style" value={style} onChange={(e) => setStyle(e.target.value as EditStyle)}>{Object.entries(styleNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><label className="primary" htmlFor="home-footage">IMPORT RAW FOOTAGE</label><input id="home-footage" accept="video/*" type="file" hidden onChange={importFootage} /><button className="secondary" onClick={createProject}>NEW PROJECT</button>{project && <button className="secondary" onClick={analyze}>RUN ANALYSIS</button>}</div></section>{preview && <section className="panel"><h2>PREVIEW · {project?.assets[0]?.name}</h2><video controls preload="metadata" src={preview} style={{ width: '100%', maxHeight: 420, background: '#000' }} /></section>}<section className="grid"><article className="panel"><h2>PROJECT STATE</h2>{project ? <><strong>{project.name}</strong><p className="muted">STYLE / {styleNames[project.style]}<br />ASSETS / {project.assets.length}<br />DECISIONS / {project.decisions.length}</p></> : <div className="empty">No projects.<br />Import footage to begin.</div>}</article><article className="panel"><h2>LUNA HUD · {progress}%</h2><div className="empty">{log}</div></article><article className="panel"><h2>TIMELINE</h2><p className="muted">{log}</p><div className="timeline"><div className="track" data-label="VIDEO"><span className="clip" /></div><div className="track" data-label="AUDIO"><span className="clip" /></div><div className="track" data-label="MUSIC" /></div></article></section></main>;
}
