'use client';

import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { buildTimeline } from '@/lib/edit-engine';
import { EditStyle, Project } from '@/lib/contracts';
import { getProject, saveProject } from '@/lib/storage';

const styles: Record<EditStyle, string> = { meme: 'Meme', calm: 'Calm', competitive: 'Competitive', 'youtube-long': 'YouTube Long' };
const bgmByStyle: Record<EditStyle, string> = { meme: '/bgm/ending-theme-super-mario-world-waKumDkYrDY.mp3', competitive: '/bgm/doom-ost-e1m1-at-doom-s-gate-hell-yeah-AQPakVlltEs.mp3', calm: '/bgm/997168-and-so-it-begins-5zjgK1LfFmE.mp3', 'youtube-long': '/bgm/997168-and-so-it-begins-5zjgK1LfFmE.mp3' };
function projectId() { return new URLSearchParams(location.search).get('project'); }

export default function Workspace() {
  const [project, setProject] = useState<Project | null>(null); const [preview, setPreview] = useState(''); const [message, setMessage] = useState('Pilih raw footage untuk mulai.'); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false); const [bgmOn, setBgmOn] = useState(false); const videoRef = useRef<HTMLVideoElement>(null); const bgmRef = useRef<HTMLAudioElement>(null);
  useEffect(() => { const id = projectId(); if (!id) { location.href = '/'; return; } getProject(id).then((item) => { if (!item) return location.href = '/'; setProject(item); if (item.assets[0]?.file) setPreview(URL.createObjectURL(item.assets[0].file)); }).catch(() => location.href = '/'); }, []);
  async function importFootage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !project || !file.type.startsWith('video/')) return setMessage('Pilih file video valid.'); const next = { ...project, assets: [{ id: `${project.id}:primary-video`, name: file.name, kind: 'video' as const, durationMs: 0, sizeBytes: file.size, file }], decisions: [], clips: [], updatedAt: new Date().toISOString() }; setProject(next); setPreview(URL.createObjectURL(file)); await saveProject(next); setProgress(0); setMessage(`FOOTAGE READY // ${file.name}`); }
  async function metadata() { if (!project || !videoRef.current) return; const durationMs = Math.round(videoRef.current.duration * 1000); if (!Number.isFinite(durationMs)) return; const next = { ...project, assets: project.assets.map((asset, index) => index ? asset : { ...asset, durationMs }), updatedAt: new Date().toISOString() }; setProject(next); await saveProject(next); setMessage(`FOOTAGE READY // ${Math.round(durationMs / 1000)} detik terdeteksi`); }
  async function analyze() { if (!project?.assets.length) return setMessage('IMPORT FOOTAGE DULU'); setBusy(true); setProgress(5); try { const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId: project.id, style: project.style, durationMs: project.assets[0].durationMs }) }); if (!response.ok || !response.body) throw new Error(); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; let latest = project; while (true) { const chunk = await reader.read(); buffer += decoder.decode(chunk.value ?? new Uint8Array(), { stream: !chunk.done }); const lines = buffer.split('\n'); buffer = lines.pop() ?? ''; for (const line of lines) if (line.startsWith('data: ')) { const event = JSON.parse(line.slice(6)); setProgress(event.progress); setMessage(`${event.state} // ${event.message}`); if (event.data?.decisions) { latest = { ...latest, decisions: event.data.decisions, clips: buildTimeline(event.data.decisions, latest.style), updatedAt: new Date().toISOString() }; setProject(latest); await saveProject(latest); } } if (chunk.done) break; } setMessage(`EDIT READY // ${latest.clips.length} keep clip, ${latest.decisions.filter((d) => d.action === 'remove').length} cut`); } catch { setMessage('ANALYSIS ERROR // coba lagi'); } finally { setBusy(false); } }
  function syncCut() { const video = videoRef.current; if (!video || !project) return; const cut = project.decisions.find((d) => d.action === 'remove' && video.currentTime * 1000 >= d.sourceStartMs && video.currentTime * 1000 < d.sourceEndMs); if (cut) video.currentTime = cut.sourceEndMs / 1000; }
  function playBgm() { const audio = bgmRef.current; if (!audio) return; setBgmOn((on) => { if (on) audio.pause(); else { audio.volume = .16; audio.play().catch(() => setMessage('Klik play video dulu sebelum BGM.')); } return !on; }); }
  if (!project) return <main className="shell"><div className="empty">Loading workspace…</div></main>;
  return <main className="shell"><header className="topbar"><a className="brand" href="/">LUNA // WORKSPACE</a><a className="secondary" href={`/output?project=${project.id}`}>OUTPUT</a></header><section className="panel"><h1>{project.name}</h1><p className="muted">Style: {styles[project.style]} · cut preview + BGM.</p><div className="actions"><label className="primary" htmlFor="footage">IMPORT RAW FOOTAGE</label><input id="footage" accept="video/*,.mp4,.mov,.webm,.mkv" type="file" hidden onChange={importFootage} /><button className="secondary" disabled={busy || !project.assets.length} onClick={analyze}>{busy ? 'ANALYZING…' : 'RUN EDIT PIPELINE'}</button>{project.clips.length ? <button className="secondary" onClick={playBgm}>{bgmOn ? 'STOP BGM' : 'PLAY BGM'}</button> : null}{project.clips.length ? <a className="secondary" href={`/output?project=${project.id}`}>OPEN OUTPUT</a> : null}</div></section>{preview ? <section className="panel"><h2>EDIT PREVIEW · CUT SEGMENTS SKIPPED</h2><video ref={videoRef} controls preload="metadata" onLoadedMetadata={metadata} onTimeUpdate={syncCut} src={preview} style={{ width: '100%', maxHeight: 480, background: '#000' }} /><audio ref={bgmRef} loop src={bgmByStyle[project.style]} /></section> : null}<section className="grid"><article className="panel"><h2>LUNA HUD · {progress}%</h2><div className="empty">{message}</div></article><article className="panel"><h2>EDIT TIMELINE</h2><div className="timeline"><div className="track" data-label="VIDEO">{project.clips.map((clip) => <span className="clip" key={clip.id} title={clip.reason} />)}</div><div className="track" data-label="AUDIO" /><div className="track" data-label="BGM">{bgmOn ? <span className="clip" /> : null}</div></div></article><article className="panel"><h2>PIPELINE</h2>{project.decisions.length ? project.decisions.map((decision) => <div className="edit-result" key={decision.id}><strong>{decision.action.toUpperCase()}</strong><span>{decision.reason}</span></div>) : <p className="muted">Run edit pipeline.</p>}</article></section></main>;
}
